trigger:
- master

pool:
  name: Default

variables:
  project-name-dev: 'ado-dockerhub'
  image-name: 'test'

stages:
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: BuildAndPushJob
    displayName: Build and Push Job
    steps:
    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        command: 'build'
        containerRegistry: 'docker-registry'
        buildContext: 'App'
        repository: '$(project-name-dev)/$(image-name)'
        Dockerfile: 'Dockerfile'
        tags: $(Build.BuildId)
    - task: Docker@2
      displayName: 'Push Docker Hub'
      inputs:
        command: 'push'
        containerRegistry: 'docker-registry'
        repository: '$(project-name-dev)/$(image-name)'
        tags: $(Build.BuildId)
